# Generated by Django 5.0 on 2024-01-02 01:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bengi_news", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="news",
            name="tags",
            field=models.ManyToManyField(to="bengi_news.tag"),
        ),
    ]
