# Generated by Django 5.0 on 2024-01-04 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bengi_news", "0002_tag_news_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="images",
        ),
        migrations.AddField(
            model_name="image",
            name="news",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="bengi_news.news",
            ),
            preserve_default=False,
        ),
    ]
